// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgvpDuh5_8gZi9hHJWlwVgXI_XvW_F91U',
    appId: '1:345939693563:web:107fb78e43e3ac9a8e055e',
    messagingSenderId: '345939693563',
    projectId: 'carveplus-cut-pro',
    authDomain: 'carveplus-cut-pro.firebaseapp.com',
    storageBucket: 'carveplus-cut-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa6bp59TYe4nggCLgGWMkEXSgC951LIaw',
    appId: '1:345939693563:android:8dd99cab96b53ee68e055e',
    messagingSenderId: '345939693563',
    projectId: 'carveplus-cut-pro',
    storageBucket: 'carveplus-cut-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXElV9YTmfHM64zHasPGd_ido1qxWNWw',
    appId: '1:345939693563:ios:e37dd50b9e8a5d7c8e055e',
    messagingSenderId: '345939693563',
    projectId: 'carveplus-cut-pro',
    storageBucket: 'carveplus-cut-pro.firebasestorage.app',
    iosBundleId: 'com.example.carveplusCutPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmXElV9YTmfHM64zHasPGd_ido1qxWNWw',
    appId: '1:345939693563:ios:e37dd50b9e8a5d7c8e055e',
    messagingSenderId: '345939693563',
    projectId: 'carveplus-cut-pro',
    storageBucket: 'carveplus-cut-pro.firebasestorage.app',
    iosBundleId: 'com.example.carveplusCutPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgvpDuh5_8gZi9hHJWlwVgXI_XvW_F91U',
    appId: '1:345939693563:web:2a287157370e66c78e055e',
    messagingSenderId: '345939693563',
    projectId: 'carveplus-cut-pro',
    authDomain: 'carveplus-cut-pro.firebaseapp.com',
    storageBucket: 'carveplus-cut-pro.firebasestorage.app',
  );
}
